if (!requireNamespace('BiocManager', quietly=TRUE))
    install.packages('BiocManager')
BiocManager::install('ShortRead')
BiocManager::install('Rbowtie2')
install.packages('curl')
install.packages('MetBrewer')
install.packages('ggplot2')
