if (!requireNamespace('BiocManager', quietly=TRUE))
    install.packages('BiocManager')
#BiocManager::install('ShortRead')
#BiocManager::install('Rbowtie2')
BiocManager::install('DECIPHER')
BiocManager::install('AssessORF')
install.packages('curl')
install.packages('MetBrewer')
install.packages('ggplot2')
install.packages('taxize')
